# -*- Ruby -*-
#
# ****  Code generated by the R2CORBA IDL Compiler ****
# R2CORBA has been developed by:
#        Remedy IT
#        Nijkerk, GLD
#        The Netherlands
#        http://www.remedy.nl  http://www.theaceorb.nl
#

module R2CORBA

  CORBA.implement('tao/BiDir_GIOP/BiDirPolicy.pidl', {}, CORBA::IDL::CLIENT_STUB) {

  module BiDirPolicy

    class BidirectionalPolicyValue < CORBA::_tc_ushort.get_type
      def BidirectionalPolicyValue._tc; @@tc_BidirectionalPolicyValue ||= CORBA::TypeCode::Alias.new('IDL:omg.org/BiDirPolicy/BidirectionalPolicyValue:1.0', 'BidirectionalPolicyValue', self, CORBA::_tc_ushort); end
    end # typedef BidirectionalPolicyValue
    NORMAL = 0
    BOTH = 1
    BIDIRECTIONAL_POLICY_TYPE = 37

    module BidirectionalPolicy  ## interface

      include CORBA::Policy

      Id = 'IDL:omg.org/BiDirPolicy/BidirectionalPolicy:1.0'.freeze
      Ids = [ Id,
              CORBA::Policy::Id ].freeze

      def BidirectionalPolicy._tc; @@tc_BidirectionalPolicy ||= CORBA::TypeCode::ObjectRef.new(Id, 'BidirectionalPolicy', self); end
      self._tc  # register typecode

      def BidirectionalPolicy._narrow(obj)
        return CORBA::Stub.create_stub(obj)._unchecked_narrow!(self)
      end

      def BidirectionalPolicy._duplicate(obj)
        obj
      end

      def _interface_repository_id
        self.class::Id
      end


      def value()
        raise ::CORBA::NO_IMPLEMENT.new(
                 'unimplemented attribute on local interface',
                 1, ::CORBA::COMPLETED_NO)
      end #of attribute get_value
    end #of interface BidirectionalPolicy
  end #of module BiDirPolicy

  } ## end of 'tao/BiDir_GIOP/BiDirPolicy.pidl'
end #of module R2CORBA

# -*- END -*-
