# -*- Ruby -*-
#
# ****  Code generated by the R2CORBA IDL Compiler ****
# R2CORBA has been developed by:
#        Remedy IT
#        Nijkerk, GLD
#        The Netherlands
#        http://www.remedy.nl  http://www.theaceorb.nl
#
require 'corba/poa.rb'
require 'TestC.rb'

module POA
  CORBA.implement('Test.idl', {}, CORBA::IDL::SERVANT_INTF) {

  module Test


    class Hello < PortableServer::Servant ## servant

      module Intf
        Id = 'IDL:Test/Hello:1.0'.freeze
        Ids = [ Id ]
        Operations = {}

        Operations.store(:get_string, {
          :result_type => CORBA._tc_string})

        def get_string()
          raise ::CORBA::NO_IMPLEMENT.new(
                   'unimplemented servant operation',
                   1, ::CORBA::COMPLETED_NO)
        end

        Operations.store(:shutdown, {})

        def shutdown()    # oneway
          raise ::CORBA::NO_IMPLEMENT.new(
                   'unimplemented servant operation',
                   1, ::CORBA::COMPLETED_NO)
        end

      end #of Intf

      Id = Intf::Id

      include_interface(PortableServer::Servant::Intf)

      include Intf

      def _this; ::Test::Hello._narrow(super); end
    end #of servant Hello
  end #of module Test

  } ## end of 'Test.idl'
end #of module POA
# -*- END -*-
